# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

name: 1.$(Date:yyyy).$(Date:MMdd).$(Rev:r)

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Powershell@2
  displayName: Update Assembly Version
  inputs:
    targetType: filePath
    filePath: 'build\Set-AssemblyInfo.ps1'
    arguments: '-BuildVersion $(Build.BuildNumber) -AssemblyInfoFile SurfaceDevCenterManager\Properties\AssemblyInfo.cs'
    workingDirectory: '.'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathToPublish: '$(System.DefaultWorkingDirectory)'
    name: 'drop'

