# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
    
    - name: Restore dependencies
      run: msbuild './SurfaceDevCenterManager/SurfaceDevCenterManager.csproj' -t:restore -property:Configuration=Release
    
    - name: Build app for release    
      run: msbuild './SurfaceDevCenterManager/SurfaceDevCenterManager.csproj' -t:build -property:Configuration=Release
